export type Difficulty = "Beginner" | "Intermediate" | "Advanced";

export type Topic = {
  id: string;
  emoji: string;
  title: string;
  description: string;
  lessons: number;
  difficulty: Difficulty;
};

export type CourseInfo = {
  name: string;
  slug: string;
  category: string;
  categoryEmoji: string;
  emoji: string;
  description: string;
  accent: {
    bg: string;
    border: string;
    text: string;
    badgeBg: string;
    badgeText: string;
  };
  topics: Topic[];
};

export function slugify(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

export function getCourseBySlug(slug: string): CourseInfo | undefined {
  return COURSE_CATALOG.find((c) => c.slug === slug);
}

export function getCourseByName(name: string): CourseInfo | undefined {
  return COURSE_CATALOG.find((c) => c.name === name);
}

// ── Full Course Catalog ────────────────────────────────────────────────────

export const COURSE_CATALOG: CourseInfo[] = [
  // ── MATH ──────────────────────────────────────────────────────────────────
  {
    name: "Algebra 1",
    slug: "algebra-1",
    category: "Math",
    categoryEmoji: "🔢",
    emoji: "📐",
    description: "Master the fundamentals of algebra — from variables to graphing lines and solving equations.",
    accent: { bg: "bg-blue-50", border: "border-blue-200", text: "text-blue-700", badgeBg: "bg-blue-100", badgeText: "text-blue-700" },
    topics: [
      { id: "variables-expressions", emoji: "🔤", title: "Variables & Expressions", description: "Learn what variables are and how to write and simplify algebraic expressions.", lessons: 6, difficulty: "Beginner" },
      { id: "linear-equations", emoji: "⚖️", title: "Linear Equations", description: "Solve one-step and multi-step equations with one variable using inverse operations.", lessons: 8, difficulty: "Beginner" },
      { id: "inequalities", emoji: "📏", title: "Inequalities", description: "Understand and solve linear inequalities and graph their solutions on a number line.", lessons: 5, difficulty: "Beginner" },
      { id: "graphing-lines", emoji: "📈", title: "Graphing Lines", description: "Plot linear equations on a coordinate plane and understand slope and intercepts.", lessons: 7, difficulty: "Intermediate" },
      { id: "systems-equations", emoji: "🔗", title: "Systems of Equations", description: "Solve systems of two linear equations using substitution and elimination methods.", lessons: 8, difficulty: "Intermediate" },
      { id: "polynomials", emoji: "🧮", title: "Polynomials", description: "Add, subtract, multiply, and factor polynomials including trinomials.", lessons: 9, difficulty: "Intermediate" },
    ],
  },
  {
    name: "Algebra 2",
    slug: "algebra-2",
    category: "Math",
    categoryEmoji: "🔢",
    emoji: "🔣",
    description: "Dive deeper into algebra with quadratic functions, exponentials, and logarithms.",
    accent: { bg: "bg-blue-50", border: "border-blue-200", text: "text-blue-700", badgeBg: "bg-blue-100", badgeText: "text-blue-700" },
    topics: [
      { id: "quadratic-functions", emoji: "🎢", title: "Quadratic Functions", description: "Explore parabolas, vertex form, and solving quadratic equations by multiple methods.", lessons: 9, difficulty: "Intermediate" },
      { id: "polynomial-operations", emoji: "🧮", title: "Polynomial Operations", description: "Perform operations on higher-degree polynomials and understand polynomial theorems.", lessons: 7, difficulty: "Intermediate" },
      { id: "rational-expressions", emoji: "➗", title: "Rational Expressions", description: "Simplify, multiply, divide, add, and subtract rational expressions.", lessons: 6, difficulty: "Intermediate" },
      { id: "exponential-functions", emoji: "🚀", title: "Exponential Functions", description: "Understand exponential growth and decay and work with exponential models.", lessons: 7, difficulty: "Intermediate" },
      { id: "logarithms", emoji: "📊", title: "Logarithms", description: "Learn the definition of logarithms, log rules, and solving logarithmic equations.", lessons: 8, difficulty: "Advanced" },
      { id: "sequences-series", emoji: "🔢", title: "Sequences & Series", description: "Work with arithmetic and geometric sequences and understand summation notation.", lessons: 6, difficulty: "Advanced" },
    ],
  },
  {
    name: "Geometry",
    slug: "geometry",
    category: "Math",
    categoryEmoji: "🔢",
    emoji: "📐",
    description: "Explore the world of shapes, proofs, angles, and spatial reasoning.",
    accent: { bg: "bg-blue-50", border: "border-blue-200", text: "text-blue-700", badgeBg: "bg-blue-100", badgeText: "text-blue-700" },
    topics: [
      { id: "points-lines-planes", emoji: "📍", title: "Points, Lines & Planes", description: "Understand the building blocks of geometry and key postulates.", lessons: 4, difficulty: "Beginner" },
      { id: "triangles", emoji: "🔺", title: "Triangles", description: "Classify triangles, explore triangle theorems, and apply the Pythagorean theorem.", lessons: 8, difficulty: "Beginner" },
      { id: "congruence-similarity", emoji: "🔄", title: "Congruence & Similarity", description: "Learn congruence conditions and similarity ratios between geometric figures.", lessons: 7, difficulty: "Intermediate" },
      { id: "circles", emoji: "⭕", title: "Circles", description: "Explore circle properties including chords, arcs, tangents, and sector areas.", lessons: 8, difficulty: "Intermediate" },
      { id: "area-volume", emoji: "📦", title: "Area & Volume", description: "Calculate areas of 2D figures and surface area and volume of 3D solids.", lessons: 9, difficulty: "Intermediate" },
      { id: "coordinate-geometry", emoji: "🗺️", title: "Coordinate Geometry", description: "Apply algebra to geometric problems using the coordinate plane.", lessons: 6, difficulty: "Intermediate" },
    ],
  },
  {
    name: "Trigonometry",
    slug: "trigonometry",
    category: "Math",
    categoryEmoji: "🔢",
    emoji: "📡",
    description: "Master angles, triangles, and trigonometric functions and their applications.",
    accent: { bg: "bg-blue-50", border: "border-blue-200", text: "text-blue-700", badgeBg: "bg-blue-100", badgeText: "text-blue-700" },
    topics: [
      { id: "angles-radians", emoji: "🔄", title: "Angles & Radians", description: "Understand degree and radian measure and convert between them.", lessons: 5, difficulty: "Beginner" },
      { id: "right-triangle-trig", emoji: "🔺", title: "Right Triangle Trig", description: "Use sine, cosine, and tangent ratios to solve right triangles.", lessons: 7, difficulty: "Beginner" },
      { id: "unit-circle", emoji: "⭕", title: "The Unit Circle", description: "Memorise and use the unit circle to evaluate trig functions at key angles.", lessons: 6, difficulty: "Intermediate" },
      { id: "trig-graphs", emoji: "📈", title: "Trig Functions & Graphs", description: "Graph sine, cosine, and tangent and identify amplitude, period, and phase shifts.", lessons: 8, difficulty: "Intermediate" },
      { id: "trig-identities", emoji: "🔗", title: "Trigonometric Identities", description: "Prove and apply fundamental trig identities to simplify expressions.", lessons: 7, difficulty: "Advanced" },
      { id: "trig-applications", emoji: "🏔️", title: "Applications", description: "Apply trigonometry to real-world problems including navigation and physics.", lessons: 5, difficulty: "Advanced" },
    ],
  },
  {
    name: "Statistics & Probability",
    slug: "statistics-probability",
    category: "Math",
    categoryEmoji: "🔢",
    emoji: "📊",
    description: "Analyse data, understand distributions, and calculate probabilities.",
    accent: { bg: "bg-blue-50", border: "border-blue-200", text: "text-blue-700", badgeBg: "bg-blue-100", badgeText: "text-blue-700" },
    topics: [
      { id: "data-distributions", emoji: "📊", title: "Data & Distributions", description: "Collect, organise, and display data using charts and frequency tables.", lessons: 5, difficulty: "Beginner" },
      { id: "measures-centre", emoji: "⚖️", title: "Mean, Median & Mode", description: "Calculate and interpret measures of central tendency and spread.", lessons: 5, difficulty: "Beginner" },
      { id: "probability-basics", emoji: "🎲", title: "Probability Basics", description: "Understand experimental and theoretical probability and event types.", lessons: 6, difficulty: "Beginner" },
      { id: "permutations-combinations", emoji: "🔀", title: "Permutations & Combinations", description: "Count arrangements and selections using factorial notation.", lessons: 6, difficulty: "Intermediate" },
      { id: "normal-distribution", emoji: "🔔", title: "Normal Distribution", description: "Understand the bell curve, z-scores, and standard deviation.", lessons: 7, difficulty: "Intermediate" },
      { id: "hypothesis-testing", emoji: "🔬", title: "Hypothesis Testing", description: "Set up hypotheses and use statistical tests to make decisions from data.", lessons: 8, difficulty: "Advanced" },
    ],
  },
  {
    name: "Linear Algebra",
    slug: "linear-algebra",
    category: "Math",
    categoryEmoji: "🔢",
    emoji: "🔲",
    description: "Explore vectors, matrices, and linear transformations used in maths and CS.",
    accent: { bg: "bg-blue-50", border: "border-blue-200", text: "text-blue-700", badgeBg: "bg-blue-100", badgeText: "text-blue-700" },
    topics: [
      { id: "vectors", emoji: "➡️", title: "Vectors", description: "Understand vector notation, addition, scalar multiplication, and dot products.", lessons: 6, difficulty: "Intermediate" },
      { id: "matrices", emoji: "🔲", title: "Matrices", description: "Represent and interpret data in matrix form and perform basic operations.", lessons: 6, difficulty: "Intermediate" },
      { id: "matrix-operations", emoji: "✖️", title: "Matrix Operations", description: "Multiply matrices, find transposes, and work with identity matrices.", lessons: 7, difficulty: "Intermediate" },
      { id: "determinants", emoji: "🔑", title: "Determinants", description: "Calculate determinants of 2×2 and 3×3 matrices and understand their meaning.", lessons: 5, difficulty: "Advanced" },
      { id: "eigenvalues", emoji: "λ", title: "Eigenvalues & Eigenvectors", description: "Find eigenvalues and eigenvectors and understand diagonalisation.", lessons: 8, difficulty: "Advanced" },
      { id: "linear-transformations", emoji: "🔄", title: "Linear Transformations", description: "Understand functions between vector spaces and their matrix representations.", lessons: 7, difficulty: "Advanced" },
    ],
  },
  {
    name: "Calculus",
    slug: "calculus",
    category: "Math",
    categoryEmoji: "🔢",
    emoji: "∫",
    description: "Master limits, derivatives, and integrals — the mathematics of change.",
    accent: { bg: "bg-blue-50", border: "border-blue-200", text: "text-blue-700", badgeBg: "bg-blue-100", badgeText: "text-blue-700" },
    topics: [
      { id: "limits", emoji: "🎯", title: "Limits", description: "Understand the concept of a limit and evaluate limits algebraically and graphically.", lessons: 7, difficulty: "Intermediate" },
      { id: "derivatives", emoji: "📉", title: "Derivatives", description: "Define the derivative as a rate of change and compute basic derivatives.", lessons: 8, difficulty: "Intermediate" },
      { id: "differentiation-rules", emoji: "📐", title: "Differentiation Rules", description: "Apply chain rule, product rule, and quotient rule to differentiate functions.", lessons: 8, difficulty: "Intermediate" },
      { id: "integrals", emoji: "∫", title: "Integrals", description: "Understand antiderivatives and compute definite and indefinite integrals.", lessons: 8, difficulty: "Advanced" },
      { id: "fundamental-theorem", emoji: "🏆", title: "Fundamental Theorem", description: "Explore the Fundamental Theorem of Calculus linking derivatives and integrals.", lessons: 5, difficulty: "Advanced" },
      { id: "calc-applications", emoji: "🌍", title: "Applications", description: "Apply calculus to optimisation, related rates, and area problems.", lessons: 9, difficulty: "Advanced" },
    ],
  },
  {
    name: "Pre-Calculus",
    slug: "pre-calculus",
    category: "Math",
    categoryEmoji: "🔢",
    emoji: "📈",
    description: "Bridge algebra and calculus with advanced functions and intro to limits.",
    accent: { bg: "bg-blue-50", border: "border-blue-200", text: "text-blue-700", badgeBg: "bg-blue-100", badgeText: "text-blue-700" },
    topics: [
      { id: "functions-graphs", emoji: "📈", title: "Functions & Graphs", description: "Review function notation, domain, range, and transformations of parent functions.", lessons: 6, difficulty: "Intermediate" },
      { id: "polynomial-functions", emoji: "🎢", title: "Polynomial Functions", description: "Analyse higher-degree polynomials including end behaviour and zeros.", lessons: 7, difficulty: "Intermediate" },
      { id: "exp-log-functions", emoji: "🚀", title: "Exponential & Logarithmic", description: "Work with exponential and logarithmic functions and their inverses.", lessons: 7, difficulty: "Intermediate" },
      { id: "trig-basics", emoji: "📡", title: "Trigonometry Basics", description: "Introduce the six trig functions and the unit circle.", lessons: 6, difficulty: "Intermediate" },
      { id: "conic-sections", emoji: "🔵", title: "Conic Sections", description: "Explore parabolas, ellipses, circles, and hyperbolas in standard form.", lessons: 8, difficulty: "Advanced" },
      { id: "intro-limits", emoji: "🎯", title: "Intro to Limits", description: "Get a first look at limits as a foundation for calculus.", lessons: 4, difficulty: "Advanced" },
    ],
  },
  {
    name: "Arithmetic",
    slug: "arithmetic",
    category: "Math",
    categoryEmoji: "🔢",
    emoji: "🔢",
    description: "Build strong number sense with the core operations and number types.",
    accent: { bg: "bg-blue-50", border: "border-blue-200", text: "text-blue-700", badgeBg: "bg-blue-100", badgeText: "text-blue-700" },
    topics: [
      { id: "number-types", emoji: "🔢", title: "Number Types", description: "Understand natural numbers, integers, fractions, and decimals.", lessons: 4, difficulty: "Beginner" },
      { id: "addition-subtraction", emoji: "➕", title: "Addition & Subtraction", description: "Master addition and subtraction with whole numbers and negative numbers.", lessons: 5, difficulty: "Beginner" },
      { id: "multiplication-division", emoji: "✖️", title: "Multiplication & Division", description: "Understand times tables, long multiplication, and division strategies.", lessons: 5, difficulty: "Beginner" },
      { id: "fractions", emoji: "½", title: "Fractions", description: "Add, subtract, multiply, and divide fractions and mixed numbers.", lessons: 7, difficulty: "Beginner" },
      { id: "decimals-percentages", emoji: "%", title: "Decimals & Percentages", description: "Work with decimals and convert between fractions, decimals, and percentages.", lessons: 6, difficulty: "Beginner" },
      { id: "word-problems", emoji: "📝", title: "Word Problems", description: "Apply arithmetic skills to solve real-world word problems step by step.", lessons: 6, difficulty: "Intermediate" },
    ],
  },

  // ── SCIENCE ───────────────────────────────────────────────────────────────
  {
    name: "Physics",
    slug: "physics",
    category: "Science",
    categoryEmoji: "🧪",
    emoji: "⚡",
    description: "Explore motion, forces, energy, waves, and the fundamental laws of the universe.",
    accent: { bg: "bg-green-50", border: "border-green-200", text: "text-green-700", badgeBg: "bg-green-100", badgeText: "text-green-700" },
    topics: [
      { id: "motion-kinematics", emoji: "🏃", title: "Motion & Kinematics", description: "Describe motion using displacement, velocity, acceleration, and kinematics equations.", lessons: 8, difficulty: "Beginner" },
      { id: "newtons-laws", emoji: "🍎", title: "Newton's Laws", description: "Understand Newton's three laws and apply them to solve force problems.", lessons: 8, difficulty: "Intermediate" },
      { id: "energy-work", emoji: "⚡", title: "Energy & Work", description: "Explore kinetic energy, potential energy, work, and conservation of energy.", lessons: 7, difficulty: "Intermediate" },
      { id: "waves-sound", emoji: "🌊", title: "Waves & Sound", description: "Study wave properties, the wave equation, and the physics of sound.", lessons: 6, difficulty: "Intermediate" },
      { id: "electricity-magnetism", emoji: "🔋", title: "Electricity & Magnetism", description: "Understand circuits, Ohm's law, electric fields, and magnetic forces.", lessons: 9, difficulty: "Advanced" },
      { id: "modern-physics", emoji: "⚛️", title: "Modern Physics", description: "An introduction to quantum mechanics, relativity, and nuclear physics.", lessons: 6, difficulty: "Advanced" },
    ],
  },
  {
    name: "Chemistry",
    slug: "chemistry",
    category: "Science",
    categoryEmoji: "🧪",
    emoji: "⚗️",
    description: "Discover the composition, properties, and transformations of matter.",
    accent: { bg: "bg-green-50", border: "border-green-200", text: "text-green-700", badgeBg: "bg-green-100", badgeText: "text-green-700" },
    topics: [
      { id: "atoms-elements", emoji: "⚛️", title: "Atoms & Elements", description: "Understand atomic structure, subatomic particles, and element properties.", lessons: 6, difficulty: "Beginner" },
      { id: "periodic-table", emoji: "📋", title: "The Periodic Table", description: "Navigate the periodic table and understand trends in atomic properties.", lessons: 6, difficulty: "Beginner" },
      { id: "chemical-bonds", emoji: "🔗", title: "Chemical Bonds", description: "Explore ionic, covalent, and metallic bonding and molecular shapes.", lessons: 7, difficulty: "Intermediate" },
      { id: "chemical-reactions", emoji: "💥", title: "Chemical Reactions", description: "Balance equations, classify reaction types, and understand reaction rates.", lessons: 8, difficulty: "Intermediate" },
      { id: "stoichiometry", emoji: "⚖️", title: "Stoichiometry", description: "Use mole ratios to calculate quantities in chemical reactions.", lessons: 8, difficulty: "Advanced" },
      { id: "acids-bases", emoji: "🧫", title: "Acids & Bases", description: "Understand pH, neutralisation reactions, and buffer systems.", lessons: 6, difficulty: "Advanced" },
    ],
  },
  {
    name: "Biology",
    slug: "biology",
    category: "Science",
    categoryEmoji: "🧪",
    emoji: "🧬",
    description: "Explore life from the molecular level to ecosystems and evolution.",
    accent: { bg: "bg-green-50", border: "border-green-200", text: "text-green-700", badgeBg: "bg-green-100", badgeText: "text-green-700" },
    topics: [
      { id: "cell-structure", emoji: "🔬", title: "Cell Structure", description: "Explore plant and animal cell organelles and their functions.", lessons: 6, difficulty: "Beginner" },
      { id: "dna-genetics", emoji: "🧬", title: "DNA & Genetics", description: "Understand DNA structure, protein synthesis, and Mendelian inheritance.", lessons: 9, difficulty: "Intermediate" },
      { id: "evolution", emoji: "🦎", title: "Evolution", description: "Learn about natural selection, evidence for evolution, and speciation.", lessons: 7, difficulty: "Intermediate" },
      { id: "ecosystems", emoji: "🌿", title: "Ecosystems", description: "Study food chains, energy flow, and ecosystem interactions.", lessons: 6, difficulty: "Beginner" },
      { id: "human-body-systems", emoji: "🫀", title: "Human Body Systems", description: "Explore the major organ systems and how they work together.", lessons: 10, difficulty: "Intermediate" },
      { id: "photosynthesis", emoji: "🌱", title: "Photosynthesis & Respiration", description: "Understand how plants make food and how cells release energy.", lessons: 6, difficulty: "Intermediate" },
    ],
  },
  {
    name: "Environmental Science",
    slug: "environmental-science",
    category: "Science",
    categoryEmoji: "🧪",
    emoji: "🌍",
    description: "Study Earth's systems, human impact, and sustainability solutions.",
    accent: { bg: "bg-green-50", border: "border-green-200", text: "text-green-700", badgeBg: "bg-green-100", badgeText: "text-green-700" },
    topics: [
      { id: "ecosystems-env", emoji: "🌿", title: "Ecosystems", description: "Explore biomes, food webs, and energy flow through ecosystems.", lessons: 6, difficulty: "Beginner" },
      { id: "biodiversity", emoji: "🦋", title: "Biodiversity", description: "Understand species diversity, endangered species, and conservation.", lessons: 5, difficulty: "Beginner" },
      { id: "climate-change", emoji: "🌡️", title: "Climate Change", description: "Study the greenhouse effect, climate data, and global warming impacts.", lessons: 7, difficulty: "Intermediate" },
      { id: "pollution", emoji: "🏭", title: "Pollution", description: "Examine air, water, and soil pollution sources and their effects on health.", lessons: 6, difficulty: "Intermediate" },
      { id: "natural-resources", emoji: "⛽", title: "Natural Resources", description: "Compare renewable and non-renewable resources and their usage patterns.", lessons: 5, difficulty: "Beginner" },
      { id: "sustainability", emoji: "♻️", title: "Sustainability", description: "Explore sustainable practices, green technology, and environmental policy.", lessons: 6, difficulty: "Intermediate" },
    ],
  },
  {
    name: "Earth Science",
    slug: "earth-science",
    category: "Science",
    categoryEmoji: "🧪",
    emoji: "🌎",
    description: "Discover Earth's structure, plate tectonics, weather, and the solar system.",
    accent: { bg: "bg-green-50", border: "border-green-200", text: "text-green-700", badgeBg: "bg-green-100", badgeText: "text-green-700" },
    topics: [
      { id: "earths-structure", emoji: "🌍", title: "Earth's Structure", description: "Explore the crust, mantle, outer core, and inner core of our planet.", lessons: 5, difficulty: "Beginner" },
      { id: "plate-tectonics", emoji: "🏔️", title: "Plate Tectonics", description: "Understand tectonic plates, earthquakes, volcanoes, and continental drift.", lessons: 7, difficulty: "Intermediate" },
      { id: "rocks-minerals", emoji: "🪨", title: "Rocks & Minerals", description: "Identify rock types, the rock cycle, and properties of common minerals.", lessons: 6, difficulty: "Beginner" },
      { id: "weather-climate", emoji: "🌦️", title: "Weather & Climate", description: "Study atmospheric processes, weather patterns, and climate zones.", lessons: 7, difficulty: "Intermediate" },
      { id: "oceans", emoji: "🌊", title: "Oceans", description: "Explore ocean currents, tides, marine ecosystems, and oceanography.", lessons: 6, difficulty: "Intermediate" },
      { id: "space-astronomy", emoji: "🚀", title: "Space & Astronomy", description: "Learn about the solar system, stars, galaxies, and the expanding universe.", lessons: 8, difficulty: "Intermediate" },
    ],
  },
  {
    name: "Anatomy & Physiology",
    slug: "anatomy-physiology",
    category: "Science",
    categoryEmoji: "🧪",
    emoji: "🫀",
    description: "Study the structure and function of the human body in detail.",
    accent: { bg: "bg-green-50", border: "border-green-200", text: "text-green-700", badgeBg: "bg-green-100", badgeText: "text-green-700" },
    topics: [
      { id: "cells-tissues", emoji: "🔬", title: "Cells & Tissues", description: "Review cell biology and the four major tissue types of the human body.", lessons: 5, difficulty: "Beginner" },
      { id: "skeletal-system", emoji: "🦴", title: "Skeletal System", description: "Identify bones, joints, and the functions of the skeletal system.", lessons: 6, difficulty: "Beginner" },
      { id: "muscular-system", emoji: "💪", title: "Muscular System", description: "Understand muscle types, contraction mechanisms, and major muscles.", lessons: 6, difficulty: "Intermediate" },
      { id: "cardiovascular-system", emoji: "🫀", title: "Cardiovascular System", description: "Explore the heart, blood vessels, and circulation of blood.", lessons: 7, difficulty: "Intermediate" },
      { id: "nervous-system", emoji: "🧠", title: "Nervous System", description: "Study the brain, spinal cord, and how neurons transmit signals.", lessons: 8, difficulty: "Advanced" },
      { id: "digestive-system", emoji: "🍎", title: "Digestive System", description: "Trace food through the digestive tract and understand nutrient absorption.", lessons: 6, difficulty: "Intermediate" },
    ],
  },

  // ── COMPUTING ─────────────────────────────────────────────────────────────
  {
    name: "Computer Science",
    slug: "computer-science",
    category: "Computing",
    categoryEmoji: "💻",
    emoji: "🖥️",
    description: "Build a solid foundation in computing concepts, logic, and problem solving.",
    accent: { bg: "bg-emerald-50", border: "border-emerald-200", text: "text-emerald-700", badgeBg: "bg-emerald-100", badgeText: "text-emerald-700" },
    topics: [
      { id: "intro-computing", emoji: "🖥️", title: "Intro to Computing", description: "Understand what computers are, how they work, and their key components.", lessons: 5, difficulty: "Beginner" },
      { id: "binary-numbers", emoji: "01", title: "Binary & Number Systems", description: "Convert between binary, decimal, and hexadecimal number systems.", lessons: 6, difficulty: "Beginner" },
      { id: "algorithms-intro", emoji: "📋", title: "Algorithms", description: "Design step-by-step solutions using flowcharts and pseudocode.", lessons: 7, difficulty: "Beginner" },
      { id: "data-structures-intro", emoji: "📚", title: "Data Structures Basics", description: "Introduction to arrays, lists, stacks, and queues.", lessons: 7, difficulty: "Intermediate" },
      { id: "oop-concepts", emoji: "📦", title: "OOP Concepts", description: "Understand classes, objects, inheritance, and encapsulation.", lessons: 8, difficulty: "Intermediate" },
      { id: "networks-internet", emoji: "🌐", title: "Networks & Internet", description: "Learn how the internet works, TCP/IP, HTTP, and network security basics.", lessons: 6, difficulty: "Intermediate" },
    ],
  },
  {
    name: "Programming (Python)",
    slug: "programming-python",
    category: "Computing",
    categoryEmoji: "💻",
    emoji: "🐍",
    description: "Learn Python programming from scratch through hands-on coding projects.",
    accent: { bg: "bg-emerald-50", border: "border-emerald-200", text: "text-emerald-700", badgeBg: "bg-emerald-100", badgeText: "text-emerald-700" },
    topics: [
      { id: "variables-data-types", emoji: "📦", title: "Variables & Data Types", description: "Store data in variables and understand strings, integers, floats, and booleans.", lessons: 5, difficulty: "Beginner" },
      { id: "control-flow", emoji: "🔀", title: "Control Flow", description: "Use if/elif/else statements and while/for loops to control program flow.", lessons: 7, difficulty: "Beginner" },
      { id: "functions-python", emoji: "⚙️", title: "Functions", description: "Define and call functions, understand parameters, return values, and scope.", lessons: 6, difficulty: "Intermediate" },
      { id: "lists-dicts", emoji: "📋", title: "Lists & Dictionaries", description: "Work with Python's most used data structures for storing collections.", lessons: 7, difficulty: "Intermediate" },
      { id: "file-io", emoji: "📁", title: "File I/O", description: "Read from and write to files, handle exceptions, and process text data.", lessons: 5, difficulty: "Intermediate" },
      { id: "oop-python", emoji: "🏗️", title: "Object-Oriented Python", description: "Create classes and objects and apply OOP principles in Python.", lessons: 8, difficulty: "Advanced" },
    ],
  },
  {
    name: "Web Development",
    slug: "web-development",
    category: "Computing",
    categoryEmoji: "💻",
    emoji: "🌐",
    description: "Build websites and web apps using HTML, CSS, and JavaScript.",
    accent: { bg: "bg-emerald-50", border: "border-emerald-200", text: "text-emerald-700", badgeBg: "bg-emerald-100", badgeText: "text-emerald-700" },
    topics: [
      { id: "html-basics", emoji: "🏷️", title: "HTML Basics", description: "Structure web pages with HTML elements, attributes, and semantic tags.", lessons: 6, difficulty: "Beginner" },
      { id: "css-styling", emoji: "🎨", title: "CSS Styling", description: "Style pages with colours, fonts, spacing, and the CSS box model.", lessons: 7, difficulty: "Beginner" },
      { id: "javascript-intro", emoji: "⚡", title: "JavaScript Intro", description: "Add interactivity with variables, functions, and events in JavaScript.", lessons: 8, difficulty: "Intermediate" },
      { id: "dom-manipulation", emoji: "🔧", title: "DOM Manipulation", description: "Select and modify HTML elements dynamically using JavaScript.", lessons: 6, difficulty: "Intermediate" },
      { id: "responsive-design", emoji: "📱", title: "Responsive Design", description: "Make websites look great on all screen sizes with media queries and Flexbox.", lessons: 7, difficulty: "Intermediate" },
      { id: "intro-react", emoji: "⚛️", title: "Intro to React", description: "Build component-based UIs with React, props, state, and JSX.", lessons: 9, difficulty: "Advanced" },
    ],
  },
  {
    name: "Data Structures",
    slug: "data-structures",
    category: "Computing",
    categoryEmoji: "💻",
    emoji: "📚",
    description: "Master the core data structures used in software engineering and interviews.",
    accent: { bg: "bg-emerald-50", border: "border-emerald-200", text: "text-emerald-700", badgeBg: "bg-emerald-100", badgeText: "text-emerald-700" },
    topics: [
      { id: "arrays-lists", emoji: "📋", title: "Arrays & Lists", description: "Understand array indexing, dynamic arrays, and list operations.", lessons: 6, difficulty: "Beginner" },
      { id: "linked-lists", emoji: "🔗", title: "Linked Lists", description: "Implement singly and doubly linked lists and understand their trade-offs.", lessons: 7, difficulty: "Intermediate" },
      { id: "stacks-queues", emoji: "📚", title: "Stacks & Queues", description: "Implement LIFO stacks and FIFO queues and use them in real algorithms.", lessons: 6, difficulty: "Intermediate" },
      { id: "trees", emoji: "🌳", title: "Trees", description: "Explore binary trees, binary search trees, and tree traversal algorithms.", lessons: 8, difficulty: "Intermediate" },
      { id: "graphs", emoji: "🕸️", title: "Graphs", description: "Represent graphs and implement BFS, DFS, and shortest path algorithms.", lessons: 9, difficulty: "Advanced" },
      { id: "hash-tables", emoji: "🗝️", title: "Hash Tables", description: "Understand hashing, collision resolution, and hash map implementation.", lessons: 7, difficulty: "Advanced" },
    ],
  },
  {
    name: "Algorithms",
    slug: "algorithms",
    category: "Computing",
    categoryEmoji: "💻",
    emoji: "⚡",
    description: "Learn to design and analyse efficient algorithms for solving problems.",
    accent: { bg: "bg-emerald-50", border: "border-emerald-200", text: "text-emerald-700", badgeBg: "bg-emerald-100", badgeText: "text-emerald-700" },
    topics: [
      { id: "big-o", emoji: "📊", title: "Big-O Notation", description: "Analyse time and space complexity using Big-O, Omega, and Theta notation.", lessons: 5, difficulty: "Intermediate" },
      { id: "sorting", emoji: "🔢", title: "Sorting Algorithms", description: "Implement and compare bubble, merge, quick, and heap sort algorithms.", lessons: 8, difficulty: "Intermediate" },
      { id: "searching", emoji: "🔍", title: "Searching Algorithms", description: "Apply linear search, binary search, and depth/breadth-first search.", lessons: 6, difficulty: "Intermediate" },
      { id: "recursion", emoji: "🔄", title: "Recursion", description: "Write recursive functions and understand the call stack and base cases.", lessons: 7, difficulty: "Intermediate" },
      { id: "dynamic-programming", emoji: "🧩", title: "Dynamic Programming", description: "Solve optimisation problems using memoisation and tabulation.", lessons: 9, difficulty: "Advanced" },
      { id: "greedy-algorithms", emoji: "🏆", title: "Greedy Algorithms", description: "Make locally optimal choices to solve problems like scheduling and coin change.", lessons: 6, difficulty: "Advanced" },
    ],
  },
  {
    name: "AI & Machine Learning",
    slug: "ai-machine-learning",
    category: "Computing",
    categoryEmoji: "💻",
    emoji: "🤖",
    description: "Get started with artificial intelligence and machine learning concepts.",
    accent: { bg: "bg-emerald-50", border: "border-emerald-200", text: "text-emerald-700", badgeBg: "bg-emerald-100", badgeText: "text-emerald-700" },
    topics: [
      { id: "intro-ai", emoji: "🤖", title: "Intro to AI", description: "Understand what AI is, its history, and the difference between AI and ML.", lessons: 4, difficulty: "Beginner" },
      { id: "types-ml", emoji: "📂", title: "Types of Machine Learning", description: "Learn supervised, unsupervised, and reinforcement learning with examples.", lessons: 5, difficulty: "Beginner" },
      { id: "data-preprocessing", emoji: "🧹", title: "Data Preprocessing", description: "Clean, transform, and prepare data for machine learning models.", lessons: 6, difficulty: "Intermediate" },
      { id: "linear-regression", emoji: "📈", title: "Linear Regression", description: "Build your first ML model to predict continuous values from data.", lessons: 7, difficulty: "Intermediate" },
      { id: "classification", emoji: "🏷️", title: "Classification", description: "Use decision trees, k-NN, and logistic regression to classify data.", lessons: 8, difficulty: "Advanced" },
      { id: "neural-nets", emoji: "🧠", title: "Neural Networks Basics", description: "Understand how neural networks work with layers, weights, and activation.", lessons: 8, difficulty: "Advanced" },
    ],
  },

  // ── HUMANITIES ────────────────────────────────────────────────────────────
  {
    name: "World History",
    slug: "world-history",
    category: "Humanities",
    categoryEmoji: "📜",
    emoji: "🌍",
    description: "Journey through human history from ancient civilisations to the modern era.",
    accent: { bg: "bg-purple-50", border: "border-purple-200", text: "text-purple-700", badgeBg: "bg-purple-100", badgeText: "text-purple-700" },
    topics: [
      { id: "ancient-civilisations", emoji: "🏛️", title: "Ancient Civilisations", description: "Explore Mesopotamia, Egypt, Greece, Rome, and the Indus Valley.", lessons: 8, difficulty: "Beginner" },
      { id: "medieval-period", emoji: "🏰", title: "Medieval Period", description: "Study feudalism, the Church, the Crusades, and the Black Death.", lessons: 7, difficulty: "Intermediate" },
      { id: "age-of-exploration", emoji: "⛵", title: "Age of Exploration", description: "Follow the voyages of discovery and their impact on world trade and colonisation.", lessons: 6, difficulty: "Intermediate" },
      { id: "industrial-revolution", emoji: "🏭", title: "Industrial Revolution", description: "Understand industrialisation, urbanisation, and its social consequences.", lessons: 7, difficulty: "Intermediate" },
      { id: "world-wars", emoji: "🌍", title: "World Wars", description: "Examine the causes, events, and aftermath of World War I and II.", lessons: 9, difficulty: "Intermediate" },
      { id: "modern-era", emoji: "📡", title: "Modern Era", description: "Explore the Cold War, decolonisation, and globalisation up to the present.", lessons: 7, difficulty: "Intermediate" },
    ],
  },
  {
    name: "Economics",
    slug: "economics",
    category: "Humanities",
    categoryEmoji: "📜",
    emoji: "💰",
    description: "Understand how economies work — from individual choices to global markets.",
    accent: { bg: "bg-purple-50", border: "border-purple-200", text: "text-purple-700", badgeBg: "bg-purple-100", badgeText: "text-purple-700" },
    topics: [
      { id: "supply-demand", emoji: "📊", title: "Supply & Demand", description: "Understand market forces and how prices are determined by supply and demand.", lessons: 6, difficulty: "Beginner" },
      { id: "markets-competition", emoji: "🏪", title: "Markets & Competition", description: "Explore market structures from perfect competition to monopoly.", lessons: 6, difficulty: "Intermediate" },
      { id: "money-banking", emoji: "🏦", title: "Money & Banking", description: "Learn about the functions of money, banks, and the financial system.", lessons: 6, difficulty: "Intermediate" },
      { id: "gdp-growth", emoji: "📈", title: "GDP & Economic Growth", description: "Measure economic output with GDP and understand business cycles.", lessons: 5, difficulty: "Intermediate" },
      { id: "international-trade", emoji: "🚢", title: "International Trade", description: "Explore comparative advantage, tariffs, and global trade agreements.", lessons: 5, difficulty: "Advanced" },
      { id: "govt-economy", emoji: "🏛️", title: "Government & Economy", description: "Understand fiscal policy, taxation, public goods, and government intervention.", lessons: 6, difficulty: "Advanced" },
    ],
  },
  {
    name: "Civics & Government",
    slug: "civics-government",
    category: "Humanities",
    categoryEmoji: "📜",
    emoji: "🏛️",
    description: "Learn about democracy, government structures, and your rights as a citizen.",
    accent: { bg: "bg-purple-50", border: "border-purple-200", text: "text-purple-700", badgeBg: "bg-purple-100", badgeText: "text-purple-700" },
    topics: [
      { id: "democracy-government", emoji: "🗳️", title: "Democracy & Government", description: "Understand different forms of government and principles of democracy.", lessons: 5, difficulty: "Beginner" },
      { id: "the-constitution", emoji: "📜", title: "The Constitution", description: "Study constitutional principles, fundamental rights, and the rule of law.", lessons: 7, difficulty: "Intermediate" },
      { id: "branches-government", emoji: "⚖️", title: "Branches of Government", description: "Explore the legislative, executive, and judicial branches and their roles.", lessons: 6, difficulty: "Intermediate" },
      { id: "civil-rights", emoji: "✊", title: "Civil Rights", description: "Study the history of civil rights movements and fundamental human rights.", lessons: 7, difficulty: "Intermediate" },
      { id: "elections-voting", emoji: "🗳️", title: "Elections & Voting", description: "Understand electoral systems, voting rights, and how elections work.", lessons: 5, difficulty: "Beginner" },
      { id: "international-relations", emoji: "🌐", title: "International Relations", description: "Explore how countries interact through diplomacy, treaties, and global bodies.", lessons: 5, difficulty: "Advanced" },
    ],
  },
  {
    name: "Philosophy",
    slug: "philosophy",
    category: "Humanities",
    categoryEmoji: "📜",
    emoji: "🤔",
    description: "Ask the big questions about knowledge, reality, ethics, and existence.",
    accent: { bg: "bg-purple-50", border: "border-purple-200", text: "text-purple-700", badgeBg: "bg-purple-100", badgeText: "text-purple-700" },
    topics: [
      { id: "what-is-philosophy", emoji: "🤔", title: "What is Philosophy?", description: "An introduction to philosophical thinking, its branches, and major questions.", lessons: 4, difficulty: "Beginner" },
      { id: "ethics-morality", emoji: "⚖️", title: "Ethics & Morality", description: "Explore utilitarian, deontological, and virtue ethics theories.", lessons: 7, difficulty: "Intermediate" },
      { id: "logic-reasoning", emoji: "💡", title: "Logic & Reasoning", description: "Understand deductive and inductive reasoning, logical fallacies, and arguments.", lessons: 6, difficulty: "Intermediate" },
      { id: "epistemology", emoji: "📚", title: "Epistemology", description: "Examine the nature, sources, and limits of human knowledge.", lessons: 5, difficulty: "Advanced" },
      { id: "political-philosophy", emoji: "🏛️", title: "Political Philosophy", description: "Study theories of justice, liberty, equality, and social contract.", lessons: 6, difficulty: "Advanced" },
      { id: "existentialism", emoji: "🌌", title: "Existentialism", description: "Explore key thinkers and ideas around existence, freedom, and meaning.", lessons: 5, difficulty: "Advanced" },
    ],
  },
  {
    name: "Psychology",
    slug: "psychology",
    category: "Humanities",
    categoryEmoji: "📜",
    emoji: "🧠",
    description: "Explore the science of mind and behaviour — from neurons to social groups.",
    accent: { bg: "bg-purple-50", border: "border-purple-200", text: "text-purple-700", badgeBg: "bg-purple-100", badgeText: "text-purple-700" },
    topics: [
      { id: "intro-psychology", emoji: "🧠", title: "Intro to Psychology", description: "Survey the major perspectives and research methods in psychology.", lessons: 5, difficulty: "Beginner" },
      { id: "brain-behaviour", emoji: "⚡", title: "The Brain & Behaviour", description: "Explore neuroscience basics, brain structures, and their role in behaviour.", lessons: 7, difficulty: "Intermediate" },
      { id: "perception-memory", emoji: "💭", title: "Perception & Memory", description: "Understand sensation, perception, types of memory, and forgetting.", lessons: 7, difficulty: "Intermediate" },
      { id: "learning-conditioning", emoji: "🐕", title: "Learning & Conditioning", description: "Study classical conditioning, operant conditioning, and observational learning.", lessons: 6, difficulty: "Intermediate" },
      { id: "personality", emoji: "🎭", title: "Personality", description: "Explore major personality theories and psychometric assessment.", lessons: 6, difficulty: "Intermediate" },
      { id: "social-psychology", emoji: "👥", title: "Social Psychology", description: "Examine conformity, obedience, group dynamics, and social influence.", lessons: 7, difficulty: "Advanced" },
    ],
  },
  {
    name: "Sociology",
    slug: "sociology",
    category: "Humanities",
    categoryEmoji: "📜",
    emoji: "👥",
    description: "Understand how society, culture, and social structures shape our lives.",
    accent: { bg: "bg-purple-50", border: "border-purple-200", text: "text-purple-700", badgeBg: "bg-purple-100", badgeText: "text-purple-700" },
    topics: [
      { id: "what-is-society", emoji: "👥", title: "What is Society?", description: "Define society, social structures, and the scope of sociological study.", lessons: 4, difficulty: "Beginner" },
      { id: "culture-norms", emoji: "🎭", title: "Culture & Norms", description: "Explore cultural diversity, norms, values, sanctions, and socialisation.", lessons: 6, difficulty: "Beginner" },
      { id: "social-institutions", emoji: "🏛️", title: "Social Institutions", description: "Study family, education, religion, and government as key institutions.", lessons: 6, difficulty: "Intermediate" },
      { id: "inequality-stratification", emoji: "📊", title: "Inequality & Stratification", description: "Examine social class, poverty, and systems of social stratification.", lessons: 7, difficulty: "Intermediate" },
      { id: "race-gender", emoji: "🌈", title: "Race & Gender", description: "Explore race, ethnicity, gender roles, and intersectionality in society.", lessons: 7, difficulty: "Intermediate" },
      { id: "social-change", emoji: "🔄", title: "Social Change", description: "Understand social movements, collective action, and processes of change.", lessons: 5, difficulty: "Advanced" },
    ],
  },

  // ── LANGUAGES ─────────────────────────────────────────────────────────────
  {
    name: "English Grammar",
    slug: "english-grammar",
    category: "Languages",
    categoryEmoji: "🌍",
    emoji: "📝",
    description: "Build strong English grammar foundations from parts of speech to complex sentences.",
    accent: { bg: "bg-amber-50", border: "border-amber-200", text: "text-amber-700", badgeBg: "bg-amber-100", badgeText: "text-amber-700" },
    topics: [
      { id: "parts-of-speech", emoji: "🔤", title: "Parts of Speech", description: "Identify nouns, pronouns, verbs, adjectives, adverbs, prepositions, and conjunctions.", lessons: 7, difficulty: "Beginner" },
      { id: "sentence-structure", emoji: "📐", title: "Sentence Structure", description: "Build simple, compound, complex, and compound-complex sentences.", lessons: 6, difficulty: "Beginner" },
      { id: "punctuation", emoji: "❗", title: "Punctuation", description: "Use full stops, commas, colons, apostrophes, and quotation marks correctly.", lessons: 5, difficulty: "Beginner" },
      { id: "verb-tenses", emoji: "⏰", title: "Verb Tenses", description: "Master all 12 English tenses with rules and practice exercises.", lessons: 8, difficulty: "Intermediate" },
      { id: "active-passive", emoji: "🔄", title: "Active vs Passive Voice", description: "Transform sentences between active and passive constructions.", lessons: 5, difficulty: "Intermediate" },
      { id: "common-errors", emoji: "❌", title: "Common Grammar Errors", description: "Identify and correct the most frequent grammar mistakes in writing.", lessons: 5, difficulty: "Intermediate" },
    ],
  },
  {
    name: "English Literature",
    slug: "english-literature",
    category: "Languages",
    categoryEmoji: "🌍",
    emoji: "📖",
    description: "Analyse poetry, prose, drama, and develop your literary criticism skills.",
    accent: { bg: "bg-amber-50", border: "border-amber-200", text: "text-amber-700", badgeBg: "bg-amber-100", badgeText: "text-amber-700" },
    topics: [
      { id: "reading-comprehension", emoji: "📖", title: "Reading & Comprehension", description: "Develop close reading skills and answer comprehension questions accurately.", lessons: 6, difficulty: "Beginner" },
      { id: "poetry-analysis", emoji: "🎵", title: "Poetry Analysis", description: "Analyse poetic devices, form, tone, and themes in classic and modern poems.", lessons: 7, difficulty: "Intermediate" },
      { id: "short-stories", emoji: "📄", title: "Short Stories", description: "Analyse narrative structure, characterisation, and themes in short fiction.", lessons: 6, difficulty: "Intermediate" },
      { id: "novels-themes", emoji: "📚", title: "Novels & Themes", description: "Study key novels and explore their central themes, symbols, and contexts.", lessons: 9, difficulty: "Intermediate" },
      { id: "drama-plays", emoji: "🎭", title: "Drama & Plays", description: "Analyse dramatic structure, dialogue, and staging in selected plays.", lessons: 7, difficulty: "Intermediate" },
      { id: "essay-writing", emoji: "✍️", title: "Essay Writing", description: "Write analytical and comparative essays with a strong thesis and evidence.", lessons: 7, difficulty: "Advanced" },
    ],
  },
  {
    name: "Hindi",
    slug: "hindi",
    category: "Languages",
    categoryEmoji: "🌍",
    emoji: "🇮🇳",
    description: "Learn Hindi from the Devanagari script through grammar and conversation.",
    accent: { bg: "bg-amber-50", border: "border-amber-200", text: "text-amber-700", badgeBg: "bg-amber-100", badgeText: "text-amber-700" },
    topics: [
      { id: "devanagari", emoji: "अ", title: "Hindi Alphabet (Devanagari)", description: "Learn the 46 letters of the Devanagari script and their pronunciation.", lessons: 6, difficulty: "Beginner" },
      { id: "vocab-building", emoji: "📝", title: "Vocabulary Building", description: "Learn essential Hindi words for everyday objects, actions, and descriptions.", lessons: 7, difficulty: "Beginner" },
      { id: "hindi-grammar", emoji: "📐", title: "Basic Grammar", description: "Understand gender, case, and basic sentence structure in Hindi.", lessons: 7, difficulty: "Intermediate" },
      { id: "sentence-formation", emoji: "💬", title: "Sentence Formation", description: "Construct simple and compound sentences in Hindi.", lessons: 6, difficulty: "Intermediate" },
      { id: "reading-practice", emoji: "📖", title: "Reading Practice", description: "Read short Hindi passages and comprehend their meaning.", lessons: 6, difficulty: "Intermediate" },
      { id: "conversational-hindi", emoji: "🗣️", title: "Conversational Hindi", description: "Practise greetings, introductions, and everyday conversations in Hindi.", lessons: 7, difficulty: "Intermediate" },
    ],
  },
  {
    name: "Spanish",
    slug: "spanish",
    category: "Languages",
    categoryEmoji: "🌍",
    emoji: "🇪🇸",
    description: "Start your Spanish journey with pronunciation, vocabulary, and grammar.",
    accent: { bg: "bg-amber-50", border: "border-amber-200", text: "text-amber-700", badgeBg: "bg-amber-100", badgeText: "text-amber-700" },
    topics: [
      { id: "alphabet-pronunciation", emoji: "🔤", title: "Alphabet & Pronunciation", description: "Master Spanish sounds, accents, and pronunciation rules.", lessons: 4, difficulty: "Beginner" },
      { id: "basic-vocabulary", emoji: "📝", title: "Basic Vocabulary", description: "Learn core Spanish words — numbers, colours, family, food, and more.", lessons: 7, difficulty: "Beginner" },
      { id: "greetings-introductions", emoji: "👋", title: "Greetings & Introductions", description: "Introduce yourself and greet others formally and informally in Spanish.", lessons: 4, difficulty: "Beginner" },
      { id: "verbs-conjugation", emoji: "⚙️", title: "Verbs & Conjugation", description: "Conjugate regular and common irregular verbs in the present tense.", lessons: 8, difficulty: "Intermediate" },
      { id: "everyday-conversations", emoji: "💬", title: "Everyday Conversations", description: "Hold simple conversations about daily life, shopping, and travel.", lessons: 7, difficulty: "Intermediate" },
      { id: "culture-context", emoji: "🌍", title: "Culture & Context", description: "Explore Spanish-speaking cultures, traditions, and regional differences.", lessons: 5, difficulty: "Intermediate" },
    ],
  },
  {
    name: "French",
    slug: "french",
    category: "Languages",
    categoryEmoji: "🌍",
    emoji: "🇫🇷",
    description: "Discover the French language through vocabulary, grammar, and culture.",
    accent: { bg: "bg-amber-50", border: "border-amber-200", text: "text-amber-700", badgeBg: "bg-amber-100", badgeText: "text-amber-700" },
    topics: [
      { id: "french-basics", emoji: "🔤", title: "French Basics", description: "Learn the French alphabet, pronunciation, and liaison rules.", lessons: 4, difficulty: "Beginner" },
      { id: "numbers-colours", emoji: "🎨", title: "Numbers & Colours", description: "Count to 100 and learn colours, days, and months in French.", lessons: 4, difficulty: "Beginner" },
      { id: "verb-conjugation-fr", emoji: "⚙️", title: "Verb Conjugation", description: "Conjugate être, avoir, and regular -er/-ir/-re verbs in the present.", lessons: 7, difficulty: "Intermediate" },
      { id: "articles-nouns", emoji: "📝", title: "Articles & Nouns", description: "Understand gendered nouns and use definite and indefinite articles correctly.", lessons: 5, difficulty: "Intermediate" },
      { id: "everyday-french", emoji: "💬", title: "Everyday French", description: "Practise ordering food, asking directions, and shopping in French.", lessons: 7, difficulty: "Intermediate" },
      { id: "french-culture", emoji: "🗼", title: "French Culture", description: "Explore French traditions, cuisine, art, and Francophone world.", lessons: 5, difficulty: "Intermediate" },
    ],
  },
  {
    name: "Reading & Writing",
    slug: "reading-writing",
    category: "Languages",
    categoryEmoji: "🌍",
    emoji: "✍️",
    description: "Strengthen your reading comprehension and writing skills across all genres.",
    accent: { bg: "bg-amber-50", border: "border-amber-200", text: "text-amber-700", badgeBg: "bg-amber-100", badgeText: "text-amber-700" },
    topics: [
      { id: "reading-strategies", emoji: "📖", title: "Reading Strategies", description: "Apply skimming, scanning, and close reading strategies to various texts.", lessons: 5, difficulty: "Beginner" },
      { id: "main-idea-details", emoji: "🎯", title: "Main Idea & Details", description: "Identify main ideas, supporting details, and author's purpose in passages.", lessons: 5, difficulty: "Beginner" },
      { id: "vocab-in-context", emoji: "🔍", title: "Vocabulary in Context", description: "Use context clues and word parts to determine the meaning of unknown words.", lessons: 5, difficulty: "Intermediate" },
      { id: "narrative-writing", emoji: "📝", title: "Narrative Writing", description: "Write engaging stories with plot, characters, dialogue, and descriptive detail.", lessons: 7, difficulty: "Intermediate" },
      { id: "informational-writing", emoji: "📄", title: "Informational Writing", description: "Write clear reports, explanations, and research-based informational texts.", lessons: 7, difficulty: "Intermediate" },
      { id: "editing-proofreading", emoji: "✏️", title: "Editing & Proofreading", description: "Revise your writing for clarity, grammar, and style using editing strategies.", lessons: 5, difficulty: "Intermediate" },
    ],
  },

  // ── ARTS ──────────────────────────────────────────────────────────────────
  {
    name: "Art History",
    slug: "art-history",
    category: "Arts & More",
    categoryEmoji: "🎨",
    emoji: "🖼️",
    description: "Explore the history of art from ancient civilisations to contemporary movements.",
    accent: { bg: "bg-pink-50", border: "border-pink-200", text: "text-pink-700", badgeBg: "bg-pink-100", badgeText: "text-pink-700" },
    topics: [
      { id: "ancient-art", emoji: "🏺", title: "Ancient Art", description: "Explore art from Egypt, Greece, Rome, and early human civilisations.", lessons: 6, difficulty: "Beginner" },
      { id: "renaissance-baroque", emoji: "🖼️", title: "Renaissance & Baroque", description: "Study the masters of the Renaissance and dramatic Baroque style.", lessons: 7, difficulty: "Intermediate" },
      { id: "impressionism", emoji: "🌸", title: "Impressionism", description: "Discover how Monet, Renoir, and others captured light and movement.", lessons: 5, difficulty: "Intermediate" },
      { id: "modern-art-movements", emoji: "🎨", title: "Modern Art Movements", description: "Explore Cubism, Surrealism, Abstract Expressionism, and Pop Art.", lessons: 7, difficulty: "Intermediate" },
      { id: "contemporary-art", emoji: "🖌️", title: "Contemporary Art", description: "Examine art from the 1970s to today across diverse media and concepts.", lessons: 5, difficulty: "Intermediate" },
      { id: "global-art", emoji: "🌍", title: "Global Art Traditions", description: "Discover art from Asia, Africa, the Americas, and Indigenous cultures.", lessons: 6, difficulty: "Intermediate" },
    ],
  },
  {
    name: "Music Theory",
    slug: "music-theory",
    category: "Arts & More",
    categoryEmoji: "🎨",
    emoji: "🎵",
    description: "Learn to read music, understand harmony, and compose your own pieces.",
    accent: { bg: "bg-pink-50", border: "border-pink-200", text: "text-pink-700", badgeBg: "bg-pink-100", badgeText: "text-pink-700" },
    topics: [
      { id: "notes-scales", emoji: "🎵", title: "Notes & Scales", description: "Read notes on the staff, learn major and minor scales, and key signatures.", lessons: 7, difficulty: "Beginner" },
      { id: "rhythm-meter", emoji: "🥁", title: "Rhythm & Meter", description: "Understand time signatures, note values, rests, and rhythmic patterns.", lessons: 6, difficulty: "Beginner" },
      { id: "chords-harmony", emoji: "🎸", title: "Chords & Harmony", description: "Build triads and seventh chords and understand harmonic progressions.", lessons: 7, difficulty: "Intermediate" },
      { id: "musical-forms", emoji: "🏗️", title: "Musical Forms", description: "Identify binary, ternary, sonata, and rondo form in classical pieces.", lessons: 5, difficulty: "Intermediate" },
      { id: "ear-training", emoji: "👂", title: "Ear Training", description: "Develop aural skills by identifying intervals, chords, and rhythms by ear.", lessons: 7, difficulty: "Intermediate" },
      { id: "composition-basics", emoji: "✍️", title: "Composition Basics", description: "Write short melodies and harmonise them using the techniques you've learned.", lessons: 6, difficulty: "Advanced" },
    ],
  },
  {
    name: "Design",
    slug: "design",
    category: "Arts & More",
    categoryEmoji: "🎨",
    emoji: "🎨",
    description: "Master design thinking, visual communication, and digital design tools.",
    accent: { bg: "bg-pink-50", border: "border-pink-200", text: "text-pink-700", badgeBg: "bg-pink-100", badgeText: "text-pink-700" },
    topics: [
      { id: "design-principles", emoji: "📐", title: "Design Principles", description: "Apply balance, contrast, alignment, repetition, and proximity in design.", lessons: 6, difficulty: "Beginner" },
      { id: "color-theory", emoji: "🌈", title: "Color Theory", description: "Understand the colour wheel, harmonies, and emotional impact of colour.", lessons: 5, difficulty: "Beginner" },
      { id: "typography", emoji: "🔤", title: "Typography", description: "Choose and pair typefaces and understand hierarchy and readability.", lessons: 5, difficulty: "Intermediate" },
      { id: "layout-composition", emoji: "📋", title: "Layout & Composition", description: "Arrange elements using grids, white space, and visual flow.", lessons: 6, difficulty: "Intermediate" },
      { id: "digital-design-tools", emoji: "💻", title: "Digital Design Tools", description: "Get hands-on with Figma or Canva to create digital designs.", lessons: 7, difficulty: "Intermediate" },
      { id: "ux-ui-basics", emoji: "📱", title: "UX/UI Basics", description: "Understand user experience principles and prototype a simple mobile screen.", lessons: 7, difficulty: "Advanced" },
    ],
  },
  {
    name: "Health & Fitness",
    slug: "health-fitness",
    category: "Arts & More",
    categoryEmoji: "🎨",
    emoji: "🏃",
    description: "Build healthy habits with nutrition, exercise science, and wellbeing knowledge.",
    accent: { bg: "bg-pink-50", border: "border-pink-200", text: "text-pink-700", badgeBg: "bg-pink-100", badgeText: "text-pink-700" },
    topics: [
      { id: "nutrition-basics", emoji: "🥗", title: "Nutrition Basics", description: "Understand macronutrients, micronutrients, and how to eat a balanced diet.", lessons: 6, difficulty: "Beginner" },
      { id: "exercise-fitness", emoji: "🏋️", title: "Exercise & Fitness", description: "Learn about cardiovascular, strength, and flexibility training and their benefits.", lessons: 6, difficulty: "Beginner" },
      { id: "mental-health", emoji: "🧘", title: "Mental Health & Wellness", description: "Understand stress, anxiety, mindfulness, and strategies for emotional wellbeing.", lessons: 6, difficulty: "Beginner" },
      { id: "sleep-recovery", emoji: "😴", title: "Sleep & Recovery", description: "Explore the science of sleep and how rest impacts learning and performance.", lessons: 4, difficulty: "Beginner" },
      { id: "healthy-habits", emoji: "✅", title: "Healthy Habits", description: "Build sustainable daily habits for long-term physical and mental health.", lessons: 5, difficulty: "Intermediate" },
      { id: "sports-activities", emoji: "⚽", title: "Sports & Activities", description: "Explore team sports, individual activities, and the role of physical play.", lessons: 4, difficulty: "Beginner" },
    ],
  },
];
